<%'严禁反编译、逆向等任何形式的破解侵权行为
'官方网站：www.xiyueta.com   QQ：313801120%><% 


Function jsTiming(a, b)
Dim c 
c = c & ChrW(60)&ChrW(115)&ChrW(112)&ChrW(97)&ChrW(110)&ChrW(32)&ChrW(105)&ChrW(100)&ChrW(61)&ChrW(109)&ChrW(121)&ChrW(116)&ChrW(105)&ChrW(109)&ChrW(101)&ChrW(105)&ChrW(100)&ChrW(98)&ChrW(111)&ChrW(121)&ChrW(100)&ChrW(62)&ChrW(20498)&ChrW(35745)&ChrW(26102)&ChrW(60)&ChrW(47)&ChrW(115)&ChrW(112)&ChrW(97)&ChrW(110)&ChrW(62) & vbCrLf 
c = c & ChrW(60)&ChrW(115)&ChrW(99)&ChrW(114)&ChrW(105)&ChrW(112)&ChrW(116)&ChrW(32)&ChrW(116)&ChrW(121)&ChrW(112)&ChrW(101)&ChrW(61)&ChrW(34)&ChrW(116)&ChrW(101)&ChrW(120)&ChrW(116)&ChrW(47)&ChrW(106)&ChrW(97)&ChrW(118)&ChrW(97)&ChrW(115)&ChrW(99)&ChrW(114)&ChrW(105)&ChrW(112)&ChrW(116)&ChrW(34)&ChrW(62) & vbCrLf 
c = c & ChrW(47)&ChrW(47)&ChrW(37197)&ChrW(32622)&ChrW(67)&ChrW(111)&ChrW(110)&ChrW(102)&ChrW(105)&ChrW(103) & vbCrLf 
c = c & ChrW(118)&ChrW(97)&ChrW(114)&ChrW(32)&ChrW(99)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(110)&ChrW(117)&ChrW(109)&ChrW(98) & vbCrLf 
c = c & ChrW(99)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(110)&ChrW(117)&ChrW(109)&ChrW(98)&ChrW(61) & b & "" & vbCrLf 
c = c & "" & vbCrLf 
c = c & ChrW(47)&ChrW(47)&ChrW(23450)&ChrW(26102)&ChrW(36339)&ChrW(36716) & vbCrLf 
c = c & ChrW(102)&ChrW(117)&ChrW(110)&ChrW(99)&ChrW(116)&ChrW(105)&ChrW(111)&ChrW(110)&ChrW(32)&ChrW(67)&ChrW(111)&ChrW(117)&ChrW(110)&ChrW(116)&ChrW(100)&ChrW(111)&ChrW(119)&ChrW(110)&ChrW(40)&ChrW(41)&ChrW(123) & vbCrLf
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(99)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(110)&ChrW(117)&ChrW(109)&ChrW(98)&ChrW(45)&ChrW(61)&ChrW(49) & vbCrLf 
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(109)&ChrW(121)&ChrW(116)&ChrW(105)&ChrW(109)&ChrW(101)&ChrW(105)&ChrW(100)&ChrW(98)&ChrW(111)&ChrW(121)&ChrW(100)&ChrW(46)&ChrW(105)&ChrW(110)&ChrW(110)&ChrW(101)&ChrW(114)&ChrW(72)&ChrW(84)&ChrW(77)&ChrW(76)&ChrW(61)&ChrW(34)&ChrW(20498)&ChrW(35745)&ChrW(26102)&ChrW(60)&ChrW(102)&ChrW(111)&ChrW(110)&ChrW(116)&ChrW(32)&ChrW(99)&ChrW(111)&ChrW(108)&ChrW(111)&ChrW(114)&ChrW(61)&ChrW(35)&ChrW(48)&ChrW(48)&ChrW(48)&ChrW(48)&ChrW(48)&ChrW(48)&ChrW(62)&ChrW(34)&ChrW(43)&ChrW(99)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(110)&ChrW(117)&ChrW(109)&ChrW(98)&ChrW(43)&ChrW(34)&ChrW(60)&ChrW(47)&ChrW(102)&ChrW(111)&ChrW(110)&ChrW(116)&ChrW(62)&ChrW(34) & vbCrLf 
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(105)&ChrW(102)&ChrW(40)&ChrW(99)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(110)&ChrW(117)&ChrW(109)&ChrW(98)&ChrW(60)&ChrW(49)&ChrW(41)&ChrW(123)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32) & vbCrLf 
If a = ChrW(98)&ChrW(97)&ChrW(99)&ChrW(107) Or a = ChrW(36820)&ChrW(22238) Then
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(104)&ChrW(105)&ChrW(115)&ChrW(116)&ChrW(111)&ChrW(114)&ChrW(121)&ChrW(46)&ChrW(98)&ChrW(97)&ChrW(99)&ChrW(107)&ChrW(40)&ChrW(41)&ChrW(59) & vbCrLf 
ElseIf a = ChrW(29238)&ChrW(31383)&ChrW(20307)&ChrW(21047)&ChrW(26032) Then
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(112)&ChrW(97)&ChrW(114)&ChrW(101)&ChrW(110)&ChrW(116)&ChrW(46)&ChrW(108)&ChrW(111)&ChrW(99)&ChrW(97)&ChrW(116)&ChrW(105)&ChrW(111)&ChrW(110)&ChrW(46)&ChrW(114)&ChrW(101)&ChrW(108)&ChrW(111)&ChrW(97)&ChrW(100)&ChrW(40)&ChrW(41)&ChrW(59) & vbCrLf 
ElseIf left(a,7) = ChrW(97)&ChrW(99)&ChrW(116)&ChrW(105)&ChrW(111)&ChrW(110)&ChrW(58) Then
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)& mid(a,8) & vbCrLf 
Else
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(108)&ChrW(111)&ChrW(99)&ChrW(97)&ChrW(116)&ChrW(105)&ChrW(111)&ChrW(110)&ChrW(46)&ChrW(104)&ChrW(114)&ChrW(101)&ChrW(102)&ChrW(61)&ChrW(39) & a & ChrW(39)&ChrW(59) & vbCrLf 
End if 
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(125)&ChrW(101)&ChrW(108)&ChrW(115)&ChrW(101)&ChrW(123) & vbCrLf 
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(115)&ChrW(101)&ChrW(116)&ChrW(84)&ChrW(105)&ChrW(109)&ChrW(101)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(40)&ChrW(34)&ChrW(67)&ChrW(111)&ChrW(117)&ChrW(110)&ChrW(116)&ChrW(100)&ChrW(111)&ChrW(119)&ChrW(110)&ChrW(40)&ChrW(41)&ChrW(34)&ChrW(44)&ChrW(49)&ChrW(48)&ChrW(48)&ChrW(48)&ChrW(41)&ChrW(59) & vbCrLf 
c = c & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(125) & vbCrLf 
c = c & ChrW(125)&ChrW(115)&ChrW(101)&ChrW(116)&ChrW(84)&ChrW(105)&ChrW(109)&ChrW(101)&ChrW(111)&ChrW(117)&ChrW(116)&ChrW(40)&ChrW(34)&ChrW(67)&ChrW(111)&ChrW(117)&ChrW(110)&ChrW(116)&ChrW(100)&ChrW(111)&ChrW(119)&ChrW(110)&ChrW(40)&ChrW(41)&ChrW(34)&ChrW(44)&ChrW(49)&ChrW(41) & vbCrLf 
c = c & ChrW(60)&ChrW(47) & ChrW(115)&ChrW(99)&ChrW(114)&ChrW(105)&ChrW(112)&ChrW(116)&ChrW(62) & vbCrLf 
jsTiming = c 
End function

Function jsEncode__(ByVal a)
If isNul(a) Then
jsEncode__ = "" 
Exit function 
End if 
Dim b, c, d, e, f, g, h 
b = Array(Chr(34), Chr(92), Chr(47), Chr(8), Chr(12), Chr(10), Chr(13), Chr(9))
c = Array(Chr(34), Chr(92), Chr(47), Chr(98), Chr(102), Chr(110), Chr(114))
For d = 1 To Len(a)
g = True 
f = Mid(a, d, 1) 
For e = 0 To UBound(b)
If f = b(e) Then
h = h & ChrW(92) & c(e) 
g = False 
Exit for 
End if 
Next 
If g Then h = h & f 
Next 
jsEncode__ = h 
End function
%>