<%'严禁反编译、逆向等任何形式的破解侵权行为
'官方网站：www.xiyueta.com   QQ：313801120%><% 

sub aboutAuthor()
dim a 
a = a & ChrW(60)&ChrW(112)&ChrW(114)&ChrW(101)&ChrW(62) & vbCrLf 
a = a & ChrW(20316)&ChrW(32773)&ChrW(65306)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(67)&ChrW(79)&ChrW(77) & vbCrLf 
a = a & ChrW(32852)&ChrW(31995)&ChrW(26041)&ChrW(24335) & vbCrLf 
a = a & ChrW(81)&ChrW(81)&ChrW(65306)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48) & vbCrLf 
a = a & ChrW(37038)&ChrW(31665)&ChrW(65306)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48)&ChrW(64)&ChrW(113)&ChrW(113)&ChrW(46)&ChrW(99)&ChrW(111)&ChrW(109) & vbCrLf 
a = a & ChrW(24494)&ChrW(20449)&ChrW(65306)&ChrW(109)&ChrW(113)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48) & vbCrLf 
a = a & ChrW(20132)&ChrW(27969)&ChrW(32676)&ChrW(51)&ChrW(53)&ChrW(57)&ChrW(49)&ChrW(53)&ChrW(49)&ChrW(48)&ChrW(48)&ChrW(40)&ChrW(32676)&ChrW(37324)&ChrW(24050)&ChrW(26377)&ChrW(20960)&ChrW(30334)&ChrW(20154)&ChrW(41) & vbCrLf  
a = a & "" & vbCrLf 
a = a & ChrW(19994)&ChrW(21153)&ChrW(21450)&ChrW(29305)&ChrW(38271) & vbCrLf 
a = a & ChrW(31934)&ChrW(36890)&ChrW(65)&ChrW(83)&ChrW(80)&ChrW(44)&ChrW(80)&ChrW(72)&ChrW(80)&ChrW(44)&ChrW(86)&ChrW(66)&ChrW(31243)&ChrW(24207)&ChrW(24320)&ChrW(21457)&ChrW(65292)&ChrW(29420)&ChrW(31435)&ChrW(24320)&ChrW(21457)&ChrW(20986)&ChrW(19968)&ChrW(22871)&ChrW(65)&ChrW(83)&ChrW(80)&ChrW(32593)&ChrW(31449)&ChrW(21518)&ChrW(21488)&ChrW(21644)&ChrW(86)&ChrW(66)&ChrW(36741)&ChrW(21161)&ChrW(36719)&ChrW(20214)&ChrW(12290) & vbCrLf 
a = a & ChrW(29087)&ChrW(32451)&ChrW(25484)&ChrW(25569)&ChrW(72)&ChrW(84)&ChrW(77)&ChrW(76)&ChrW(12289)&ChrW(68)&ChrW(73)&ChrW(86)&ChrW(12289)&ChrW(67)&ChrW(83)&ChrW(83)&ChrW(12289)&ChrW(74)&ChrW(83) & vbCrLf 
a = a & ChrW(29087)&ChrW(32451)&ChrW(20351)&ChrW(29992)&ChrW(68)&ChrW(114)&ChrW(101)&ChrW(97)&ChrW(109)&ChrW(119)&ChrW(101)&ChrW(97)&ChrW(118)&ChrW(101)&ChrW(114)&ChrW(12289)&ChrW(70)&ChrW(105)&ChrW(114)&ChrW(101)&ChrW(119)&ChrW(111)&ChrW(114)&ChrW(107)&ChrW(115)&ChrW(12289)&ChrW(32)&ChrW(70)&ChrW(108)&ChrW(97)&ChrW(115)&ChrW(104)&ChrW(12289)&ChrW(80)&ChrW(104)&ChrW(111)&ChrW(116)&ChrW(111)&ChrW(115)&ChrW(104)&ChrW(111)&ChrW(112)&ChrW(31561)&ChrW(36719)&ChrW(20214) & vbCrLf    
a = a & ChrW(33258)&ChrW(35273)&ChrW(80)&ChrW(72)&ChrW(80)&ChrW(12289)&ChrW(65)&ChrW(110)&ChrW(100)&ChrW(114)&ChrW(111)&ChrW(105)&ChrW(100)&ChrW(31561)&ChrW(32534)&ChrW(31243)&ChrW(35821)&ChrW(35328) & vbCrLf 
a = a & "" & vbCrLf 
a = a & "" & vbCrLf 
a = a & ChrW(33258)&ChrW(25105)&ChrW(35780)&ChrW(20215) & vbCrLf 
a = a & ChrW(33258)&ChrW(23398)&ChrW(33021)&ChrW(21147)&ChrW(24378)&ChrW(12289)&ChrW(26032)&ChrW(30693)&ChrW(35782)&ChrW(25509)&ChrW(21463)&ChrW(24555)&ChrW(12289)&ChrW(21191)&ChrW(20110)&ChrW(38754)&ChrW(23545)&ChrW(22256)&ChrW(38590)&ChrW(65292)&ChrW(25954)&ChrW(20110)&ChrW(25361)&ChrW(25112)&ChrW(12290) & vbCrLf 
a = a & ChrW(60)&ChrW(47)&ChrW(112)&ChrW(114)&ChrW(101)&ChrW(62) & vbCrLf 
response.write(a) : response.end() 
end sub 

function authorInfo(a)
authorInfo = handleAuthorInfo(a, ChrW(97)&ChrW(115)&ChrW(112)) 
end function 

function handleAuthorInfo(a, b)
dim c, d, e 
if b = ChrW(112)&ChrW(104)&ChrW(112) then
d = ChrW(47) 
else
e = ChrW(39) 
end if 
c = e & d & ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42) & vbCrLf 
if a <> "" then c = c & e & ChrW(32)&ChrW(32)&ChrW(25991)&ChrW(20214)&ChrW(65306) & a & vbCrLf 
c = c & e & ChrW(20316)&ChrW(32773)&ChrW(65306)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(67)&ChrW(79)&ChrW(77)&ChrW(32)&ChrW(12304)&ChrW(31934)&ChrW(36890)&ChrW(65)&ChrW(83)&ChrW(80)&ChrW(47)&ChrW(80)&ChrW(72)&ChrW(80)&ChrW(47)&ChrW(65)&ChrW(83)&ChrW(80)&ChrW(46)&ChrW(78)&ChrW(69)&ChrW(84)&ChrW(47)&ChrW(86)&ChrW(66)&ChrW(47)&ChrW(74)&ChrW(83)&ChrW(47)&ChrW(65)&ChrW(110)&ChrW(100)&ChrW(114)&ChrW(111)&ChrW(105)&ChrW(100)&ChrW(47)&ChrW(70)&ChrW(108)&ChrW(97)&ChrW(115)&ChrW(104)&ChrW(65292)&ChrW(20132)&ChrW(27969)&ChrW(47)&ChrW(21512)&ChrW(20316)&ChrW(21487)&ChrW(32852)&ChrW(31995)&ChrW(41) & vbCrLf 
c = c & e & ChrW(29256)&ChrW(26435)&ChrW(65306)&ChrW(28304)&ChrW(20195)&ChrW(30721)&ChrW(20813)&ChrW(36153)&ChrW(20844)&ChrW(24320)&ChrW(65292)&ChrW(21508)&ChrW(31181)&ChrW(29992)&ChrW(36884)&ChrW(22343)&ChrW(21487)&ChrW(20351)&ChrW(29992)&ChrW(12290)&ChrW(32) & vbCrLf 
c = c & e & ChrW(21019)&ChrW(24314)&ChrW(65306) & format_Time(now(), 2) & vbCrLf 
c = c & e & ChrW(32852)&ChrW(31995)&ChrW(65306)&ChrW(81)&ChrW(81)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48)&ChrW(32)&ChrW(32)&ChrW(20132)&ChrW(27969)&ChrW(32676)&ChrW(51)&ChrW(53)&ChrW(57)&ChrW(49)&ChrW(53)&ChrW(49)&ChrW(48)&ChrW(48)&ChrW(40)&ChrW(32676)&ChrW(37324)&ChrW(24050)&ChrW(26377)&ChrW(20960)&ChrW(30334)&ChrW(20154)&ChrW(41)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(37038)&ChrW(31665)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48)&ChrW(64)&ChrW(113)&ChrW(113)&ChrW(46)&ChrW(99)&ChrW(111)&ChrW(109)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(20010)&ChrW(20154)&ChrW(20027)&ChrW(39029)&ChrW(32)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(46)&ChrW(99)&ChrW(111)&ChrW(109) & vbCrLf 
c = c & e & ChrW(26356)&ChrW(22810)&ChrW(24110)&ChrW(21161)&ChrW(65292)&ChrW(25991)&ChrW(26723)&ChrW(65292)&ChrW(26356)&ChrW(26032)&ChrW(12288)&ChrW(35831)&ChrW(21152)&ChrW(32676)&ChrW(40)&ChrW(51)&ChrW(53)&ChrW(57)&ChrW(49)&ChrW(53)&ChrW(49)&ChrW(48)&ChrW(48)&ChrW(41)&ChrW(25110)&ChrW(27983)&ChrW(35272)&ChrW(40)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(46)&ChrW(99)&ChrW(111)&ChrW(109)&ChrW(41)&ChrW(33719)&ChrW(24471) & vbCrLf 
c = c & e & ChrW(42)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(80)&ChrW(111)&ChrW(119)&ChrW(101)&ChrW(114)&ChrW(101)&ChrW(100)&ChrW(32)&ChrW(98)&ChrW(121)&ChrW(32)&ChrW(80)&ChrW(65)&ChrW(65)&ChrW(74)&ChrW(67)&ChrW(77)&ChrW(83)&ChrW(32) & vbCrLf 
c = c & e & ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42)&ChrW(42) & d & vbCrLf 
handleAuthorInfo = c 
end function 
function authorInfo2()
dim a 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(39)&ChrW(39)&ChrW(39) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(40)&ChrW(48)&ChrW(32)&ChrW(48)&ChrW(41) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(43)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(111)&ChrW(79)&ChrW(79)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(40)&ChrW(95)&ChrW(41)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(43) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(80)&ChrW(111)&ChrW(119)&ChrW(101)&ChrW(114)&ChrW(101)&ChrW(100)&ChrW(32)&ChrW(66)&ChrW(121)&ChrW(32)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(32)&ChrW(45)&ChrW(32)&ChrW(119)&ChrW(119)&ChrW(119)&ChrW(46)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(46)&ChrW(99)&ChrW(111)&ChrW(109)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(81)&ChrW(81)&ChrW(58)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(67)&ChrW(114)&ChrW(101)&ChrW(97)&ChrW(116)&ChrW(105)&ChrW(111)&ChrW(110)&ChrW(58)& format_Time(now(),2) &ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(67)&ChrW(77)&ChrW(83)&ChrW(32)& version &ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(43)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(111)&ChrW(79)&ChrW(79)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(43) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(95)&ChrW(95)&ChrW(124)&ChrW(95)&ChrW(95)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(124)&ChrW(32)&ChrW(124)&ChrW(124) & vbCrLf 
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(111)&ChrW(111)&ChrW(79)&ChrW(32)&ChrW(79)&ChrW(111)&ChrW(111) & vbCrLf 
authorInfo2 = a 
end function 

function authorXiyuetaCOM()
dim a 
a=ChrW(39)&ChrW(35)&ChrW(31105)&ChrW(27490)&ChrW(33258)&ChrW(21160)&ChrW(26356)&ChrW(26032)&ChrW(24403)&ChrW(21069)&ChrW(25991)&ChrW(20214)&ChrW(39)&ChrW(32)&ChrW(32)&ChrW(35)&ChrW(21495)&ChrW(21435)&ChrW(25481)&ChrW(20195)&ChrW(34920)&ChrW(27492)&ChrW(25991)&ChrW(20214)&ChrW(19981)&ChrW(34987)&ChrW(31243)&ChrW(24207)&ChrW(33258)&ChrW(21160)&ChrW(26356)&ChrW(26032)&ChrW(26367)&ChrW(25442)&ChrW(25481) & vbcrlf & vbcrlf
a = a & ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(39)&ChrW(39)&ChrW(39) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(40)&ChrW(48)&ChrW(32)&ChrW(48)&ChrW(41) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(43)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(111)&ChrW(79)&ChrW(79)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(40)&ChrW(95)&ChrW(41)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(43) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(97)&ChrW(117)&ChrW(116)&ChrW(104)&ChrW(111)&ChrW(114)&ChrW(58)&ChrW(88)&ChrW(73)&ChrW(89)&ChrW(85)&ChrW(69)&ChrW(84)&ChrW(65)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(81)&ChrW(81)&ChrW(58)&ChrW(51)&ChrW(49)&ChrW(51)&ChrW(56)&ChrW(48)&ChrW(49)&ChrW(49)&ChrW(50)&ChrW(48)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(119)&ChrW(119)&ChrW(119)&ChrW(46)&ChrW(120)&ChrW(105)&ChrW(121)&ChrW(117)&ChrW(101)&ChrW(116)&ChrW(97)&ChrW(46)&ChrW(99)&ChrW(111)&ChrW(109)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(43)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(111)&ChrW(79)&ChrW(79)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(45)&ChrW(43) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(95)&ChrW(95)&ChrW(124)&ChrW(95)&ChrW(95)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(124)&ChrW(124)&ChrW(32)&ChrW(124)&ChrW(124) & vbCrLf 
a = a & ChrW(39)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(32)&ChrW(111)&ChrW(111)&ChrW(79)&ChrW(32)&ChrW(79)&ChrW(111)&ChrW(111) & vbCrLf 
authorXiyuetaCOM=a
end function
%>  
